/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "I2CM.h"
#include "I2CM_I2C.h"
#include "I2CM_PINS.h"
#include "I2CM_I2C_PVT.h"
#include "I2CM_PVT.h"
#include "I2CM_BOOT.h"
#include "pin_incl_x.h"
#include "pin_incl_x_aliases.h"
#include "Clk_Timer.h"
#include "Timer.h"
#include "UART.h"
#include "UART_SPI_UART.h"
#include "UART_PINS.h"
#include "UART_SPI_UART_PVT.h"
#include "UART_PVT.h"
#include "UART_BOOT.h"
#include "Clk_Timer_1.h"
#include "TimerHumidityTemp.h"
#include "HumidityTempIsr.h"
#include "ADC_SAR_SEQ.h"
#include "Pin_Vin.h"
#include "Pin_Vin_aliases.h"
#include "I2CM_SCBCLK.h"
#include "I2CM_sda.h"
#include "I2CM_sda_aliases.h"
#include "I2CM_scl.h"
#include "I2CM_scl_aliases.h"
#include "I2CM_SCB_IRQ.h"
#include "UART_SCBCLK.h"
#include "UART_tx.h"
#include "UART_tx_aliases.h"
#include "UART_rx.h"
#include "UART_rx_aliases.h"
#include "ADC_SAR_SEQ_IRQ.h"
#include "ADC_SAR_SEQ_intClock.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyLFClk.h"
#include "cy_em_eeprom.h"

/*[]*/

